name:                rpg-server-engine
version:             0.1.0.0
github:              "kirkiano/rpg-server-engine-haskell"
license:             BSD3
author:              "Kirkian O"
maintainer:          "kirkiano137@gmail.com"
copyright:           "2012-2019 Kirkian O"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            RPG server

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/kirkiano/rpg-server-engine-haskell#readme>

dependencies:
- aeson                == 1.2.3.0
- base                 >= 4.7 && < 5
- base64-bytestring    == 1.0.0.1
- bouncer              == 0.1.2.2
- bytestring           == 0.10.8.2
- case-insensitive     == 1.2.0.10
- concurrent-extra     == 0.7.0.11
- containers           == 0.5.10.2
- cookie               == 0.4.4
- cryptonite           == 0.24
- either               == 4.5
- filepath             == 1.4.1.2
- forwarder            == 0.1.4.0
- hedis                == 0.9.12
- HUnit                == 1.6.0.0
- loggit               == 0.1.0.1
- misc-utils           == 0.2.0.3
- monad-control        == 1.0.2.2
- network              == 2.6.3.2
- network-simple       == 0.4.1
- optparse-applicative == 0.14.0.0
- postgresql-simple    == 0.5.3.0
- process              == 1.6.1.0
- regex-compat         == 0.95.1
- resource-pool        == 0.2.3.2
- send-receive         == 0.2.2.6
- stm                  == 2.4.4.1
- text                 == 1.2.2.2
- thread-mailbox       == 0.1.2.0
- time                 == 1.7.0.1
- transformers         == 0.5.2.0
- unix                 == 2.7.2.2
- utf8-string          == 1.0.1.1
- websockets           == 0.12.2.0
- Workflow             == 0.8.3

library:
  source-dirs: src

executables:
  rpg-server-engine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rpg-server-engine

tests:
  rpg-server-engine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rpg-server-engine
