FROM docker.kirkiano.org/finance-server-front-express-base

# Port to listener
EXPOSE 3000

# Environment variables
ENV NODE_ENV production
ENV PORT 3000
ENV PUBLIC_PATH "/"

RUN npm build

# Main command
CMD [ "npm", "start"]